package com.company;

public class Apartment {

    // Instance Variables - each instance of the class Programmer will have a copy these variables.
    // id - this will be autogenerated when added to the database.
    private int id;
    private String address;
    private double cost;
    private String bedroomNumber;
    private String maintenance;
    private boolean parkingSpace;
    


    // this constructor does not accept an ID. Use this constructor when first creating objects. The Id will be generated
    // when the object is stored in the database - Auto-increment
    public Apartment(String a, double c, String n,  String m, boolean p) {
        this.address = a;
        this.cost = c;
        this.bedroomNumber = n;
        this.maintenance = m;
        this.parkingSpace = p;
        


    }

    // Use this constructor when you are taking data from the database, it accepts an ID.
    public Apartment(int id, String a, double c, String n,  String m, boolean p) {
        this.id = id;
        this.address = a;
        this.cost = c;
        this.bedroomNumber = n;
        this.maintenance = m;
        this.parkingSpace = p;

    }

    public int getId()
    {
        return id;
    }

    public void setId(int id){
        this.id = id;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public double getCost() {
        return cost;
    }

    public void setCost(double cost) {
        this.cost = cost;
    }

    public String getBedroomNumber() {
        return bedroomNumber;
    }

    public void setBedroomNumber(String rooms) {
        this.bedroomNumber = rooms;
    }

    public String getMaintenance() {
        return maintenance;
    }

    public void setMaintenance(String maintenance) {
        this.maintenance = maintenance;
    }

    public boolean getParkingSpace() {
        return parkingSpace;
    }

    public void setParkingSpace(boolean spaces) {
        this.parkingSpace = spaces;
    }


    // special method that will return a string version of the object, you should format and return everything
    @Override
    public String toString()
    {
        return "Apartment ID : " + id + "  Address : "   + address + " Cost: " + cost +  " Bed Room Number : " + bedroomNumber + " Maintenance : " + maintenance + " Parking Spaces : " + parkingSpace + "\n" ;
    }
}
